name: disabled-runtime-i18n-latest-main-apk
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  disabled:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo disabled
